// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx5XgwEZYS-0m0qSk4x3YVBx1KNpEASLY',
    appId: '1:141793349554:web:c7ae24e02765a4793c5eab',
    messagingSenderId: '141793349554',
    projectId: 'sync-app-b85ba',
    authDomain: 'sync-app-b85ba.firebaseapp.com',
    storageBucket: 'sync-app-b85ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX6dapTzV6Arj_XW-OaaSL61QSLIwVipA',
    appId: '1:141793349554:android:f0b6c25b1bc4931a3c5eab',
    messagingSenderId: '141793349554',
    projectId: 'sync-app-b85ba',
    storageBucket: 'sync-app-b85ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGkrDzQRVNOKJa4TMy7OQcOGzzD8_nGeI',
    appId: '1:141793349554:ios:7c6355a126c26fd03c5eab',
    messagingSenderId: '141793349554',
    projectId: 'sync-app-b85ba',
    storageBucket: 'sync-app-b85ba.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGkrDzQRVNOKJa4TMy7OQcOGzzD8_nGeI',
    appId: '1:141793349554:ios:7c6355a126c26fd03c5eab',
    messagingSenderId: '141793349554',
    projectId: 'sync-app-b85ba',
    storageBucket: 'sync-app-b85ba.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx5XgwEZYS-0m0qSk4x3YVBx1KNpEASLY',
    appId: '1:141793349554:web:b25bd6afa9bffaa13c5eab',
    messagingSenderId: '141793349554',
    projectId: 'sync-app-b85ba',
    authDomain: 'sync-app-b85ba.firebaseapp.com',
    storageBucket: 'sync-app-b85ba.firebasestorage.app',
  );
}
